### ISSUE TITLE
${parameter} shall be substituted anywhere in strings

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-jsonpreprocessor#69] opened 2023-06-12 13:50 UTC
${parameter} shall be substituted anywhere in strings with it's content's string repesentation.
Reference is TML's substitution.
This includes data structure references with [""] and "."-syntax.
Please discuss with Cuong how to make a elegant solution for "."-syntax

e.g.
```
{
  "param1" : "key1",
  "param2" : "abc${param1}def",
  "param3${param1} : "abc${param1}def{$param2}"
}
```

must result ins:
```
param1 : "key1"
param2 : "abckey1def"
param3key1 : "abckey1defabckey1def"
```

**Comment by HolQue** [comment] 2023-06-13 15:19
Are you sure about: `"param2" : "abc${param1}def",` ?

I would expect: `"param2" : "abc${params}['global']['param1']def",`
Or: `"param2" : "abc${params.global.param1}def",`

**Comment by test-fullautomation** [comment] 2023-06-13 15:41
Hi Holger,
hm... we have here still a mix between generic preprocessing and semantics required for robotframework-testsuitesmanagement.
We need to discuss this before implementation.
Thank you,
 Thomas

**Comment by HolQue** [comment] 2023-06-13 15:43
What shall happen in these cases?

```
"dict_val" : {"keyA" : "keyA_val", "keyB" : "keyB_val"},
"list_val" : ["A", 1, True],

"param2" : "abc${params.global.dict_val}def",
"param3" : "abc${params.global.list_val}def",
```

With `${params.global.dict_val}` and `${params.global.list_val}` I expect to get a string representation of the Python code that generates the dictionary and the list. This might be OK, if appears on the right hand side of the colon.

But this might cause strange parameter names:

```
"param2_${params.global.dict_val}" : "abc",
"param3_${params.global.list_val}" : "def",
```

In my opinion we should have a hand on this.

Suggestion:

While resolving the possibly nested `$`-operator structure, the data types of the affected variables should be checked. In case of a composite data type is detected at any position, a flag has to be set accordingly.

Before the final substitution of a `$`-operator at the left hand side of the colon (variable name), this flag should be checked.

If the flag tells that a composite data type was involved, we know, that we might get variable names, we do not want to have (or may be invalid; how about blanks inside names?).

Possible reactions:

* Abort with error and test result is UNKNOWN.
* Accept - but with warning in log file.
* Accept - but with shortened name and warning in log file.

**Comment by test-fullautomation** [comment] 2023-06-13 15:48
Hi Holger,
"Abort with error and test result is UNKNOWN" would be my preference.
A key name assembled from a stringified data-structure makes for me no sense.
Thank you,
 Thomas

**Comment by HolQue** [comment] 2023-06-14 14:15
I still have doubts about code like his:

```
"param1" : "value",
"param2" : ${params.global.param1}
```

This is so much unintuitive.

Therefore another try to catch this topic:

I assume to have two jsonp files (with relevant parts of the path starts with a project folder):

`project/00/11/fileA.jsonp` and `project/00/11/22/fileB.jsonp`

fileA imports fileB.

How about this kind of content?

* **project/00/11/fileA.jsonp**
```
{
   "paramA" : "valA",
   "paramB" : "valB",
   "A_1" : {
              "paramA" : "valA1",
              "paramB" : "valB1"
           },
   "A_2" : {
              "paramA" : "valA2",
              "paramB" : "valB2"
           },
   // reference to parameter inside this file:
   "paramC"   : ${paramA},                     // outcome: paramC initialized with "valA"
   "paramD"   : ${A_1.paramA},                 // outcome: paramD initialized with "valA1"
   // overwrite parameter defined in this file
   "paramB" : "valB3",                         // outcome: paramB updated to "valB3"
   "[IMPORT]" : "./22/fileB.jsonp"
}
```

* **project/00/11/22/fileB.jsonp**
```
{
   // reference to parameter outside this file:
   "paramE"   : ${00.11.fileA.A_2.paramB},     // outcome: paramE initialized with "valB2"
   // overwrite parameter defined outside this file:
   ${00.11.fileA.A_2.paramB} : "valB4",
   // add new key to parameter defined outside this file:
   ${00.11.fileA.A_2.paramC} : "valC"
}
```

Assignments happen accordingly to the following rules:

* The default parameter scope is the current jsonp file.
* Every reference to a parameter defined outside the current file, requires to add the full scope to the parameter name.
* The full scope includes the path to this file outside the current file and the file name (path relative to position of projects folder).

Advantages:

* It's much easier now to detect, from where (which imported file) a value come from.
* Code is easier to understand and easier to maintain.
* "params.global" is not necessary any more.
* Introduction of a default scope (the current jsonp file) shortens the code.

At end the JsonPreprocessor should return such a resolved data structure:

```
dParams = {
   "paramA" : "valA",
   "paramB" : "valB3",
   "A_1"    : {
                 "paramA" : "valA1",
                 "paramB" : "valB1"
              },
   "A_2"    : {
                 "paramA" : "valA2",
                 "paramB" : "valB4",
                 "paramC" : "valC"
              },
   "paramC" : "valA",
   "paramD" : "valA1",
   "paramE" : "valB2"
}
```

In case of the Testsuites Management is involved, it should be under the responsibility of the Testsuites Management, to put the returned `dParams` into a proper bag, to make the values inside accessible within Robot Framework tests in the following way (like usual):

```
log    ${paramA}
log    ${A_2.paramC}
```
With this solution both worlds the Json Preprocessor and the Testsuites Management are clearly separated from each other, only `dParams` is the interface in between, and there are no syntax conflicts any more between both.

What do you think?

**Comment by namsonx** [comment] 2023-06-22 09:39
Hello Thomas,

I created the pull request #75 for this improvement.

Thank you,
Son

**Comment by HolQue** [comment] 2023-09-05 13:47
Hi Son,

the JSON code

```
{
   "param"    : [1,2,3],
   "${param}" : "value"
}
```

causes the following error message:

`'Could not set variable '[1, 2, 3]' with value 'value'! Reason: cannot assign to literal (<string>, line 1)'`

This is not helpful for users. This makes no sense. This is too much technical and does not point out exactly to what is wrong here.

The error message has to tell the user that it is not allowed to use composite data types in ${} substitutions on the left hand side of a colon (inside parameter name or dictionary key name). Because a name derived out of a stringified composite data structure don't makes sense.


Similar with this code (dictionary now):

```
{
   "param"    : {"A" : 1, "B" : 2},
   "${param}" : "value"
}
```

But now the JsonPreprocessor returns values instead of an exception:

```
[DICT] (2/1) > {param} [DICT] (2/1) > {A} [INT]  :  1
[DICT] (2/1) > {param} [DICT] (2/2) > {B} [INT]  :  2
[DICT] (2/2) > {{'A': 1, 'B': 2}} [STR]  :  'value'
```

Like already mentioned above: Such a parameter name `{'A': 1, 'B': 2}` makes no sense.

**Comment by namsonx** [comment] 2023-09-06 11:27
Hello Holger,

Thank you for your finding!
For the case:
```
{
   "param"    : [1,2,3],
   "${param}" : "value"
}
```
I will handle this error in JsonPreprocessor package to make it more clearer.

For the case:
```
{
   "param"    : {"A" : 1, "B" : 2},
   "${param}" : "value"
}
```
Yes, it make no sense to define the parameter name ```"{'A': 1, 'B': 2}"```. It happens because we not yet define the naming convention for a parameter name in configuration file. Could you please help us define a naming convention for parameter names in jsonp?

Thank you,
Son

**Comment by HolQue** [comment] 2023-09-06 13:13
Hi Son,

yes, we should have a naming convention. But this use case should be handled `before` a naming convention check.

It's quite easy: In case you detect a dollar operator expression inside a parameter name or inside a dictionary key name, you have to check the data type of the affected parameter, that shall be inserted. In case of the data type is not `int`, not `float` and not `str`, you throw an error, that it is not allowed to do the `${}` substitution with composite data types.

Checking also a naming convention would be the last step after all allowed substitutions are done.

**Comment by namsonx** [comment] 2023-09-08 09:10
Hi Holger,

Thank you for the hint! I will implement a datatype checking before doing the substitution.

Thank you,
Son

**Comment by test-fullautomation** [comment] 2023-09-25 13:22
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by HolQue** [comment] 2023-09-26 13:57
Things still need to be fixed.

See also

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/111

**Comment by HolQue** [comment] 2023-10-09 13:34
Deeply related to

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/111

that was shifted to 0.10.0. Therefore this ticket should also be shifted to 0.10.0.

Main topic still open: substitution of composite data types in parameter and key names.

**Comment by test-fullautomation** [comment] 2023-10-09 13:36
shifted to 0.10.0

**Comment by namsonx** [comment] 2023-11-02 02:18
Hello Holger, Hello Thomas,

The ticket #111 was fixed on stabi branch. After Holger reviewed and verified ticket #111, we can close this ticket as well.

Thank you,
Son

**Comment by HolQue** [comment] 2024-01-10 12:45
Hi Son,

still a small side effect ;-)

The code:

```
"param"    : [1,2,3],
"${param}" : "value"
```

and also

```
"param"    : {"A" : 1, "B" : 2},
"${param}" : "value"
```

causes
`
Found expression '' with at least one parameter of ...`

with empty `''`.

Most probably caused by the fact that the entire expression inside the double quotes

`"${param}"`

is a dollar operator expression.

In case of it's a composite string, like

`"_${param}_"`

the error message is complete

`Found expression '_${param}_' with at least one ...`

**Comment by namsonx** [comment] 2024-01-11 10:23
Hello Holger,

Thank you very much for the finding!
I have just pushed the tiny change [b2d74260aca](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/181/commits/b2d74260aca90850c5cd6933391b327711c21eea) to fix this small side effect.
The fix now is available on stabi branch.

Thank you,
Son

**Comment by HolQue** [comment] 2024-01-19 17:42
Retest successful. Issue can be closed.

**Comment by namsonx** [comment] 2024-01-24 07:49
merged to develop branch

**Closed as completed** 2024-03-05 13:39 UTC
Labels: enhancement, new feature, prio 2, 0.10.0
